controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_image:
    path: /image/{id}
    controller: App\Controller\AppController::image
